[package]
name = "analytic-gallop"
version = "0.1.0"
edition = "2021"

[lib]
name = "analytic_gallop"
crate-type = ["cdylib"]

[dependencies]


[dependencies.pyo3]
version = "0.22"
features = ["extension-module"]





